# This workflow, on each of the supported versions of CPython, as
# well as on some version of PyPy, installs the library and runs
# its doctests and the version number consistency check.

name: Install and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        python-version:
        - "3.11"
        - "3.10"
        - "3.9"
        - "3.8"
        - "3.7"
        - "3.6"
        - "2.7"
        - "pypy3"

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install
      run: |
        python -m pip install --upgrade pip
        python -m pip install .
    - name: Run doctests
      run: |
        python run-doctests.py
    - name: Check version number consistency
      run: |
        python check-ver-consistency.py
